### ISSUE TITLE
docker dev environment broken

### ISSUE THREAD

**Issue by DavHau** [lutris/website#397]
Executing `docker-compose up` on a freshly cloned repo results in the error `ModuleNotFoundError: No module named 'croppie'`:
```
web_1  | ./manage.py runserver 0.0.0.0:8000
web_1  | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe0c57c1e18>
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 225, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py", line 112, in inner_run
web_1  |     autoreload.raise_last_exception()
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 248, in raise_last_exception
web_1  |     raise _exception[1]
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 327, in execute
web_1  |     autoreload.check_errors(django.setup)()
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 225, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 89, in populate
web_1  |     app_config = AppConfig.create(entry)
web_1  |   File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 90, in create
web_1  |     module = import_module(entry)
web_1  |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
web_1  | ModuleNotFoundError: No module named 'croppie'
```

EDIT: I investigated a litttle bit further and the problem seems solved after executing `docker-compose make deps`. This should not be necessary since one can see that the dependencies already get installed during the docker build. Seems like something breaks the dependency installation afterwards again.

**Comment by DavHau** [comment]
Also when i surf the website, the content under /static/js and /static/css cannot be loaded. Can somebody give a hint on how to fix this?
